export const keywords = [
  "Phoenix Trade Exports",
  "Phoenix export company",
  "Indian export company",
  "global exporters from India",
  "exporters and suppliers India",
  "international trade company India",
  "bulk product exporters",
  "B2B export supplier India",
  "fresh agricultural products export",
  "fresh vegetables exporter India",
  "Indian vegetable exporter",
  "farm fresh vegetables for export",
  "onion exporter India",
  "potato exporter India",
  "tomato exporter India",
  "green chilli exporter",
  "okra exporter India",
  "drumstick exporter India",
  "bulk vegetables export",
  "organic produce exporter India",
  "marine products exporter India",
  "seafood exporter India",
  "frozen shrimp exporter",
  "frozen fish exporter India",
  "IQF shrimp exporter",
  "vannamei shrimp exporter",
  "black tiger shrimp exporter",
  "frozen seafood supplier",
  "export quality seafood India",
  "coconut exporter India",
  "fresh coconut export",
  "coconut water exporter",
  "virgin coconut oil exporter",
  "cold pressed coconut oil exporter",
  "coconut coir exporter",
  "coconut husk exporter",
  "coco peat exporter India",
  "dehydrated food exporter",
  "dehydrated vegetable powders",
  "fruit powder exporter India",
  "banana powder exporter",
  "moringa powder exporter",
  "turmeric powder exporter",
  "ginger powder exporter",
  "spray dried food powders",
  "freeze dried food exporter",
  "banana fiber fabric exporter",
  "sustainable fabric exporter India",
  "eco friendly textiles exporter",
  "natural fiber fabrics India",
  "banana fiber textile supplier",
  "handloom fabric exporter",
  "organic textile exporter India",
  "banana fiber fabric exporter",
  "sustainable fabric exporter India",
  "eco friendly textiles exporter",
  "natural fiber fabrics India",
  "banana fiber textile supplier",
  "handloom fabric exporter",
  "organic textile exporter India",

  "export supplier for bulk orders",
  "wholesale export supplier India",
  "international buyers India exporter",
  "custom packaging export",
  "private label export supplier",
  "global B2B sourcing India",
  "export enquiry India",
  "buy directly from exporter",

  "export company Andhra Pradesh",
  "exporter from India to USA",
  "exporter from India to UAE",
  "exporter from India to Europe",
  "HACCP certified exporter",
  "ISO certified export company",
  "phytosanitary certified exporter",
];
